spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      #-------------指向注册中心的http请求的uri前缀为 lb://, websocket请求的uri前缀为ws://
      routes:
      #------------------------------system--------------------------------
      - id: system
        uri: lb://SYSTEM
        predicates:
        - Path= /system/**
      #这里是将/system/xx的请求转发到 lb://system/xx 会去掉system的前缀，这个功能与zuul的stripPrefix（去掉前缀）相同
      # - RewritePath的方法位于/org/springframework/cloud/gateway/filter/factory/RewritePathGatewayFilterFactory.java
        filters:
        - StripPrefix=1
      #-------------------------------auth------------------------------------
      - id: app
        uri: lb://app
        predicates:
        - Path= /app/**
        filters:
        - StripPrefix=1
#        - RewritePath=/auth/(?<segment>.*), /$\{segment}

server:
  port: 40000

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:30000/eureka/

ribbon:
  ConnectTimeout: 60000
  ReadTimeout:  60000

hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false
                isolation:
                    thread:
                        timeoutInMilliseconds:  60000