server:
  port: 30002

eureka:
  server:
    port: 30000
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 45
  client:
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.server.port}/eureka/


ribbon:
  ConnectTimeout: 60000
  ReadTimeout:  60000

hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: true
                isolation:
                    thread:
                        timeoutInMilliseconds:  20000

spring:
    datasource:
        initialSize: 1
        minIdle: 1
        maxActive: 5
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://mydemo:3306/sabah?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: mydemo
        password: mydemo
    redis:
        database: 0
        host: mydemo
        port: 6379
        password: mydemo

logging:
    level:
      com.netflix: ERROR

